version: '3'

services:
    lodex:
        container_name: lodex-apil
        build:
            context: .
        image: inistcnrs/lodex-apil:12.21.0
        user: '${UID}:${GID}'
        environment:
            http_proxy: ${http_proxy}
            https_proxy: ${https_proxy}
            EZMASTER_MONGODB_HOST_PORT: 'mongo:27017'
            EZMASTER_TECHNICAL_NAME: 'lodex'
            no_proxy: 'localhost,127.0.0.1,'
        links:
            - mongo
        ports:
            - 3000:3000

    mongo:
        container_name: lodex-database-1
        image: mongo:4.4.4
        ports:
            - 27017:27017
